Решение для задания 1(доработанное)
maksimlazukhin/lazuhin_september2021 pull request #9
Opened 2021-10-17 16:37 UTC by maksimlazukhin

Создано пустое решение 1
1)создано пустое решение задания 1-1
2)создано пустое решение задания 1-2
3)создано пустое решение задания 1-3

2021-10-17 16:41 UTC, maksimlazukhin commented
Задание 1-1 
1)условие
![задание1-1](https://user-images.githubusercontent.com/91391045/137636699-3929487e-2aeb-427d-8246-0916f2b7ec86.jpg)
 2)консоль
![консоль1-1](https://user-images.githubusercontent.com/91391045/137636711-48ec6c6c-f61e-4717-b9d5-eee1a0b4183a.jpg)
3)exel
![EXCEL1-1](https://user-images.githubusercontent.com/91391045/137636721-48cb4dd3-757e-49ce-9e7f-01f0aae37411.jpg)

2021-10-18 18:15 UTC, MarinaPaley requested changes

2021-10-18 18:15 UTC, MarinaPaley commented on Task1-1/Task1-1/Main.cpp
> +* \ breaf  a(x,y,z)
`brif`

2021-10-18 18:15 UTC, MarinaPaley commented on Task1-1/Task1-1/Main.cpp
> +* \ param x,y,z
каждый параметр отдельно

2021-10-18 18:15 UTC, MarinaPaley commented on Task1-1/Task1-1/Main.cpp
> +	double ss;
перемудрили [корень третьй степени](https://en.cppreference.com/w/cpp/numeric/math/cbrt)
если нужна временная переменная, то именуйте ее `temp`

2022-01-21 11:58 UTC, merged